### ISSUE TITLE
Failure on invitation causes infinite-loop of requests

### ISSUE THREAD

**Issue by ramonpoca** [creativechain/creativechain-universe#2]
At common.js:26, funcion inviteUser(address).

On failure this method sets a timeout and calls itself recursively. It's being called almost 1 time per second on startup, and receives an (understandable) TOO_REQUESTS response.

**Comment by ander7agar** [comment]
Fixed in https://github.com/creativechain/creativechain-universe/commit/96a6cba83a8421886fc22c9154a866109ffd5ca5.
